In [16]:
import pandas as pd
import requests
import json
import numpy as np
from datetime import datetime
pd.set_option('display.float_format', lambda x: '%.4f' % x)
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 100)

In [17]:
pd.__version__

'1.5.3'

In [18]:
df_housing = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv')

In [19]:
df_housing.shape

(20640, 10)

In [20]:
df_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [21]:
df_housing.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [22]:
df_housing[df_housing['ocean_proximity'] == 'NEAR BAY'].median_house_value.mean()

259212.31179039303

In [23]:
old_mean = df_housing.total_bedrooms.mean()
df_housing.total_bedrooms = df_housing.total_bedrooms.fillna(df_housing.total_bedrooms.mean())

In [24]:
df_housing.total_bedrooms.mean()

537.8705525375617

In [25]:
old_mean

537.8705525375618

In [105]:
X = np.array(df_housing[df_housing['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']])

In [106]:
XTX = np.matmul(X.T, X)

In [107]:
XTX_inverse = np.linalg.inv(XTX)

In [108]:
y = np.array([950, 1300, 800, 1000, 1300])

In [109]:
y

array([ 950, 1300,  800, 1000, 1300])

In [110]:
mul = np.matmul(XTX_inverse, X.T)

In [111]:
np.matmul(XTX_inverse, X.T)

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [113]:
np.matmul(mul, y)

array([23.12330961, -1.48124183,  5.69922946])